TutorSystem/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.conf.urls.defaults import *
import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TutorSystem.views.home', name='home'),
    # url(r'^TutorSystem/', include('TutorSystem.foo.urls')),
    url(r'^submittutorrequest/$', views.submit_tutor_request),
    url(r'^filltutorrequest/$', views.fill_tutor_request),
    url(r'^tutordisplay/$', views.tutordisplay),
    url(r'^detailed_info/$', views.tutorinfo),
    url(r'^home/$',views.home),
    url(r'^login/$',views.login),
    url(r'^login_success/$',views.login_success),
    url(r'^accounts/logout/$', logout,{'next_page':'/home/'}), 
    url(r'profile_change/',views.profilechange),
    url(r'password_change/',views.passwordchange),
    url(r'imagehandle/',views.imagehandle),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

TutorSystem/forms.py
from django.forms import ModelForm
from db.models import *

class SubmitRequest(ModelForm):
    class Meta:
        model = TutorRequest

db/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from db.models import *

class ProfileChangeForm(forms.Form):
    name = forms.CharField(label='Name',max_length=30, required = False)
    school = forms.CharField(label='School',max_length=40,required = False)
    subject = forms.CharField(label='Subject',required = False)
    cellphone = forms.CharField(label='Cellphone',max_length=40,required = False)
    honour = forms.CharField(label='Honour',max_length=200,required = False)
    speciality = forms.CharField(label='Speciality',max_length=200,required = False)
    additional_info =  forms.CharField(label='Additional_info',max_length=500,required = False)
    course = forms.CharField(label='Course',max_length=200,required = False)
    area = forms.CharField(label='Area',max_length=200,required = False)
    time_period = forms.CharField(label='TimePeriod')
    potrait = forms.ImageField(required = False)

TutorSystem/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import auth
from django.template import RequestContext
from django.db.models import *
from db.models import *
from db.forms import *
from forms import *
import json

def submit_tutor_request(request):
    if request.method == "GET":
        return HttpResponse("Invalid Post")
    tutor_request_form = SubmitRequest(request.POST)
    if tutor_request_form.is_valid():
        tutor_request_form.save()
        return HttpResponse("Succeeded")
    else:
        return HttpResponse("Invalid Post")

def fill_tutor_request(request):
    form = SubmitRequest()
    return render_to_response('fill_request.html', locals(), context_instance=RequestContext(request))
    

def tutorinfo(request):
    if 'user_id' in request.GET and request.GET['user_id']:
        print int(request.GET['user_id'])
        user = User.objects.get(id=int(request.GET['user_id']))
    else:
        return HttpResponse(u"no such tutor")
    return render_to_response('detailed_info.html', locals(), context_instance=RequestContext(request))

def tutordisplay(request):
    candidate = User.objects.all()
    timeslot = TimePeriod.objects.all()
#    print candidate
    if 'TimePeriod' in request.GET and request.GET['TimePeriod']:
        time_period = json.loads(request.GET['TimePeriod'])
        for time_period_id in time_period:
            candidate = candidate.filter(profile__time_period__id = time_period_id)
    if 'Subject' in request.GET and request.GET['Subject']:
        subject = json.loads(request.GET['Subject'])
        for subject_id in subject:
            candidate = candidate.filter(profile__subject__id = subject_id)
    if 'District' in request.GET and request.GET['District']:
        district = json.loads(request.GET['District'])
        for district_id in district:
            candidate = candidate.filter(profile__area__id = district_id)
    candidate.order_by('salary_per_hour')
#    print candidate
    return render_to_response('display.html', locals(), context_instance=RequestContext(request))

def home(request):
    user = request.user
    return render_to_response('home.html',locals(),context_instance=RequestContext(request))
    
def login(request):
    path = request.get_full_path()
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect("/login_success/")
        else:
            return render_to_response('login.html',{'errors':'True'},context_instance=RequestContext(request))
        request.session.modified = True
    return render_to_response('login.html', context_instance=RequestContext(request))
    
@login_required
def login_success(request):
    return render_to_response('login_success.html',locals(),context_instance=RequestContext(request))

    
@login_required
def passwordchange(request):
    user = request.user
    if request.method == 'POST':     
        if request.POST['origin'] != '' :
            if not user.check_password(request.POST['origin']):
                return render_to_response('password_change.html',{'passerror':'True'}, context_instance=RequestContext(request))    
            if request.POST['word1'] !=  request.POST['word2']:
                return render_to_response('password_change.html',{'sameerror':'True'}, context_instance=RequestContext(request))   
            if len(request.POST['word1']) < 6:
                return render_to_response('password_change.html',{'short':'True'}, context_instance=RequestContext(request))    
            user.set_password(request.POST['word1'])
            user.save()
            return render_to_response('password_change.html',{'change':'True'}, context_instance=RequestContext(request))
        else:
            return render_to_response('password_change.html',{'blank':'True'}, context_instance=RequestContext(request))
    
    return render_to_response('password_change.html',context_instance=RequestContext(request))
    
    
@login_required
def profilechange(request):
    user = request.user
    profile = user.get_profile()
    form = ProfileChangeForm(request.POST,instance=profile)
    if request.method == 'POST':   
       if form.is_valid():
           form.save()
    else:
       form = ProfileChangeForm(instance=profile)
           
    return render_to_response('profile_change.html',locals(), context_instance=RequestContext(request))

def imagehandle(request):
    user = request.user
    profile = user.get_profile()
    form = UploadImageForm(request.POST,request.FILES)
    if request.method == 'POST':
        if form.is_valid:
            #profile.potrait = request.FILES['file']
            sp = request
            sad
            profile.save()
    else:
        form = UploadImageForm()
    
    return render_to_response('image_upload_display.html',locals(), context_instance=RequestContext(request))
    

TutorSystem/templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
  
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% block special %}{% endblock %}

<head>
    <title>
    {% block title %}{% endblock%}
    </title>
</head>

<body>
    <h1>{% block head %}{% endblock%}</h1>
    
    {% block content%}Login{% endblock %}

    
</body>

<tail>
{% block tail %}{% endblock%}
</tail>

TutorSystem/templates/detailed_info.html
{% extends "base.html" %}


  {% block title %}
    Detailed Information
  {% endblock %}
  
  


  
  {% block content %}
  <th>
    <td>编号：{{user.profile.id}} </td>
    <td>姓名：{{user.profile.name}} </td>
    <td>就读学校：{{user.profile.school}}</td>
    <td>授课学科：{{user.profile.subject}} </td>
    <td>授课区域：{{user.profile.area.name}}</td>
    <td>个人简介：{{user.profile.additional_info}} </td>
    <td>获得荣誉：{{user.profile.speciality}} </td>
    <td>特长：{{user.profile.speciality}} </td>
    <td>头像：</td>
    <td>淘宝链接：{{user.profile.taobao_link}} </td>
    <td>最低时薪：{{user.profile.salary_per_hour}} </td>
    
    想要与他联系？请填写下面的信息：
  </th>
  {% endblock %}

TutorSystem/templates/display.html
{% extends "base.html" %}


  {% block title %}
    TutorDisplay
  {% endblock %}
  
  


  
  {% block content %}
  {% for item in candidate %}
  <th>
    <td>姓名：{{item.profile.name}} </td>
    <td>个人简介：{{item.profile.additional_info}} </td>
  </th>
  {% endfor %}
  {% endblock %}

TutorSystem/templates/fill_request.html
{% extends "base.html" %}


  {% block title %}
    fill your form
  {% endblock %}
  
  


  
  {% block content %}
    <form method="post" action="/submittutorrequest/">
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" />
    {%csrf_token%}
    </form>
    
  {% endblock %}

TutorSystem/templates/home.html
{% extends "base.html" %}

  {% block title %}
    Home
  {% endblock %}
  
  
  {% block head %}
    <h1>
      Welcome  {% if user.is_authenticated %}{{user.username}}{% endif %} !
    </h1>
  {% endblock %}
  
  {% block content %}
    {% if user.is_authenticated %}
      <p>
        Click <a href="/change_profile/">here</a> to change your personal info.
        <br/>
        <a href="accounts/logout/">Logout</a>
        <br/>
        <a href="password_change/">password_change</a>
        <br/>
        <a href="profile_change/">password_change</a>
      </p>
     
    {% else %}
      <p>
        Welcome!<br/>
        <a href="/login/">Login</a>
       
      </p>
      <br />
      <p>
        First time visitor? Please read the <a href="/about/">
        About</a> and <a href="/help/">Help</a> pages to
        get started.
      </p>
    {% endif %}
  {% endblock %}

TutorSystem/templates/image_upload_display.html
{% extends "base.html" %}

  {% block title %}
    User Account: Image
  {% endblock %}
  
  {% block heading %}
    <h1>Image</h1>
  {% endblock %}

  {% block content %}
    <img src = ""></img>
    <form method="post" action=".">
      {% csrf_token %}
      <table>
<tr><th><label for="id_image">Image:</label></th><td><input id="id_image" name="
image" type="file" /></td></tr>

     </table>
        <input id="submit" type="submit" value="update" />
        
    </form>
  {% endblock %}

TutorSystem/templates/login.html
{% extends "base.html" %}

{% block title%}Login{% endblock %}

{% block head %}Login{% endblock %}

{% block content%}
      {% if errors %}
      <p style = "color:red">
        用户名密码不匹配！请重试！
      </p>
    {% endif %}
    <form method="post" action="">
        {% csrf_token %}
        <p>
        <label for="id_username">用户名:</label>
        <input type="text" name="username" value="" id="username">
        </p>
        <p><label for="id_password" >密码: </label>
        <input type="password" name="password" value="" id="password">
        </p>
        <input type="hidden" name="next" value="{{ next|escape }}" />
        <input type="submit" value="login" />

    </form>

    {% endblock %}

TutorSystem/templates/login_success.html
{% extends "base.html" %}
{% block special %}
<meta http-equiv="refresh" content="5;URL=/home/">
{% endblock %}

{% block title %}
Login
{% endblock %}

{% block head %}
<h1>
User Login
</h1>
{% endblock %}

{% block content %}


<p>
    Welcome back! {{user}}.
</p>
<p>
    the page will return in 5 secconds.
</p>

<p>
<br />
click
<a href="/home/">here</a> to return to the home page immediately
</p>
{% endblock %}

TutorSystem/templates/password_change.html
{% extends "base.html" %}

  {% block title %}
    User Account: Password Change
  {% endblock %}
  
  {% block heading %}
    <h1>User Account: Password Change</h1>
  {% endblock %}

  {% block content %}
   {% if passerror %}
        <p style = "color:red">Password not correct!Try again!</p>
    {% endif %}

    

    {% if change %}
        <p style = "color:red">Change password succesfully!</p>
        <p style = "color:red">Please keep it in mind!</p>
    {% endif %}
    {% if short %}
       <p> <font color = red>Password too short!(6 characters at least)</font></p>
        {% endif %}
    <form method="post" action=".">
      {% csrf_token %}
    
      <table><tr>
        <td>Input your original password:</td>
        <td><input type = "password" name = "origin">
         {% if blank %}
        <font color = red>Should not be blank!</p>
         {% endif %}
      </tr>
      <tr>
        <td>Input your new password:</td>
        <td><input type = "password" name = "word1">
        
      </tr>
      <tr>
        <td>Input your new password again:</td>
        <td><input type = "password" name = "word2">
        {% if sameerror %}
        <font color = red>Passwords not matched!</font>
    {% endif %}
      </tr></table>
      <input id="submit" type="submit" value="update" />
    </form>
  {% endblock %}

TutorSystem/templates/profile_change.html
{% extends "base.html" %}

  {% block title %}
    User Account: Email Change
  {% endblock %}
  
  {% block heading %}
    <h1>User Account: Profile Change</h1>
  {% endblock %}

  {% block content %}
    {% if change %}
    <p style = "color:red">Change profile succesfully!</p>
    {% endif %}
    <form method="post" action=".">
      {% csrf_token %}
      <table>
      <tr><th><label for="id_name">Name:</label></th><td><input id="id_name" maxlength="30" name="name" type="text" /></td></tr>
<tr><th><label for="id_school">School:</label></th><td><input id="id_school" maxlength="40" name="school" type="text" /></td></tr>
<tr><th><label for="id_subject">Subject:</label></th><td><input id="id_subject" name="subject" type="text" /></td></tr>
<tr><th><label for="id_cellphone">Cellphone:</label></th><td><input id="id_cellphone" maxlength="40" name="cellphone" type="text" /></td></tr>
<tr><th><label for="id_honour">Honour:</label></th><td><input id="id_honour" maxlength="200" name="honour" type="text" /></td></tr>
<tr><th><label for="id_speciality">Speciality:</label></th><td><input id="id_speciality" maxlength="200" name="speciality" type="text" /></td></tr>
<tr><th><label for="id_additional_info">Additional_info:</label></th><td><input id="id_additional_info" maxlength="500" name="additional_info" type="text" /></td></tr>
<tr><th><label for="id_course">Course:</label></th><td><input id="id_course" maxlength="200" name="course" type="text" /></td></tr>
<tr><th><label for="id_area">Area:</label></th><td><input id="id_area" maxlength="200" name="area" type="text" /></td></tr>
<tr><th><label for="id_time_period">TimePeriod:</label></th><td><input id="id_time_period" name="time_period" type="text" /></td></tr>
<tr><th><label for="id_potrait">Potrait:</label></th><td><input id="id_potrait" name="potrait" type="file" /></td></tr>
        
     </table>
        <input id="submit" type="submit" value="update" />
        
    </form>
  {% endblock %}